import { MouseEventHandler } from 'react';
import styles from './index.module.css';

type IconButtonProps = {
  icon: string;
  altText?: string;
  handleClick: MouseEventHandler<HTMLButtonElement>;
} & React.ButtonHTMLAttributes<HTMLButtonElement>;

const IconButton: React.FC<IconButtonProps> = ({
  icon,
  altText,
  handleClick,
  // className,
  ...props
}) => {
  return (
    // The button className is generated by CSS modules
    <button className={styles.button} {...props} onClick={handleClick}>
    {/* The fix:
    The button's className combines the CSS module-generated button className
    with the additional class name passed through props
    <button
      className={`${styles.button} ${className}`}
      {...props}
      onClick={handleClick}
    > */}
      {/* The img className is generated by CSS modules */}
      <img src={icon} className={styles.img} alt={altText ?? 'icon button'} />
    </button>
  );
};

export default IconButton;
